import { describe, expect, it } from "vitest";
import { ConversationScrollController, type ConversationScrollTarget } from "./conversation-scroll.js";

class FrameQueue {
	private nextHandle = 1;
	private callbacks = new Map<number, FrameRequestCallback>();

	request = (callback: FrameRequestCallback): number => {
		const handle = this.nextHandle++;
		this.callbacks.set(handle, callback);
		return handle;
	};

	cancel = (handle: number): void => {
		this.callbacks.delete(handle);
	};

	flush(): void {
		const callbacks = [...this.callbacks.values()];
		this.callbacks.clear();
		for (const callback of callbacks) callback(0);
	}

	get size(): number {
		return this.callbacks.size;
	}
}

function scrollTarget(overrides: Partial<ConversationScrollTarget> = {}): ConversationScrollTarget {
	return {
		scrollTop: 700,
		scrollHeight: 1_000,
		clientHeight: 300,
		...overrides,
	};
}

function setup() {
	const frames = new FrameQueue();
	const controller = new ConversationScrollController(frames.request, frames.cancel);
	return { controller, frames };
}

describe("ConversationScrollController", () => {
	it("coalesces repeated streamed renders into one scroll write", () => {
		const { controller, frames } = setup();
		const target = scrollTarget({ scrollTop: 500 });

		controller.scrollToBottomIfNeeded(() => target);
		controller.scrollToBottomIfNeeded(() => target);

		expect(frames.size).toBe(1);
		frames.flush();
		expect(target.scrollTop).toBe(1_000);
	});

	it("stays pinned through off-bottom layout events while a frame is queued", () => {
		const { controller, frames } = setup();
		const target = scrollTarget();

		controller.scrollToBottomIfNeeded(() => target);
		target.scrollHeight = 1_200;
		controller.handleScroll(target);
		frames.flush();

		expect(target.scrollTop).toBe(1_200);
	});

	it("cancels a queued scroll as soon as the user intends to scroll up", () => {
		const { controller, frames } = setup();
		const target = scrollTarget({ scrollTop: 500 });

		controller.scrollToBottomIfNeeded(() => target);
		controller.pauseForUser();
		frames.flush();

		expect(target.scrollTop).toBe(500);
		controller.scrollToBottomIfNeeded(() => target);
		expect(frames.size).toBe(0);
	});

	it("does not repin from the scroll event generated by an older programmatic write", () => {
		const { controller, frames } = setup();
		const target = scrollTarget({ scrollTop: 500 });

		controller.scrollToBottomIfNeeded(() => target);
		frames.flush();
		controller.pauseForUser();
		controller.handleScroll(target);
		frames.flush();

		target.scrollTop = 400;
		controller.scrollToBottomIfNeeded(() => target);
		expect(frames.size).toBe(0);
		expect(target.scrollTop).toBe(400);
	});

	it("resumes following when the user returns to the bottom", () => {
		const { controller, frames } = setup();
		const target = scrollTarget({ scrollTop: 300 });

		controller.pauseForUser();
		controller.handleScroll(target);
		target.scrollTop = 700;
		controller.handleScroll(target);
		target.scrollHeight = 1_100;
		controller.scrollToBottomIfNeeded(() => target);
		frames.flush();

		expect(target.scrollTop).toBe(1_100);
	});

	it("forces the next tail position across transient session-switch scroll events", () => {
		const { controller, frames } = setup();
		const target = scrollTarget({ scrollTop: 0 });

		controller.pauseForUser();
		controller.pinToBottom();
		controller.handleScroll(target);
		controller.scrollToBottomIfNeeded(() => target);
		frames.flush();

		expect(target.scrollTop).toBe(1_000);
	});
});
